# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: "postgres"
    container_name: "kotlin_postgres"
    environment:
      POSTGRES_DB: writer-db
      POSTGRES_USER: writer-user
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"